name: 'Release'

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - uses: actions/checkout@v3

      - name: Install Deps
        uses: actions/setup-node@v3
        with:
          node-version: '14'
          cache: yarn

      - run: yarn install

      - name: Release
        run: yarn release
